### ISSUE TITLE
IGC9 AWS workshop instructions and user feedback form

### ISSUE THREAD

**Issue by JiaweiZhuang** [geoschem/geos-chem-cloud#24]
## Basic workshop information

**Time**: Thursday (05/09), 3:00-5:00 pm
**Location**:  Maxwell-Dworkin G115
**Requirement**: Bring a laptop with internet connection. To connect to WIFI, follow [Connect to Harvard Wireless as a guest](https://harvard.service-now.com/ithelp?id=kb_article&sys_id=d2c981d8371b32803dc68ff1b3990e55), "Connecting to Harvard wireless as a visitor" (second section).

Free temporary AWS accounts will be provided during the workshop. We have 30+ registered participants right now and can accommodate at most 40 people.

## Optional preparations

Here are the preparations you can do before the workshop. **You don't have to do any of those before coming**, and can instead do those during the workshop. But those steps can help you get most out of the workshop (so you can spend less time waiting for software installations, etc.)

1. **Sign-up for a GitHub account** at https://github.com/join. You will need such an account to provide workshop feedbacks (detailed later). You can further use the account to ask questions and report bugs about GEOSChem-on-cloud, on the [GitHub issue tracker](https://github.com/geoschem/geos-chem-cloud/issues). Treat it as an online forum. GitHub is also [the currently recommended way to submit your code updates](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_coding_and_debugging#Submitting_updates_for_inclusion_into_GEOS-Chem), so it is nice to have an account, anyway. Finally, consider [giving a star](https://help.github.com/articles/about-stars/) to the repositories under the [GEOS-Chem team](https://github.com/geoschem). Just click on the "star" button on the upper-right corner of each repository page. This "shows appreciation to the repository maintainer for their work".

2. **Study our Python tutorial** at https://github.com/geoschem/GEOSChem-python-tutorial, if you have no Python experience before. The workshop will involve a little bit of Python. But it is also fine to come without prior knowledge.

3. **For Windows users, install [Git-Bash](https://gitforwindows.org/)** as a Linux-like terminal. This is mentioned in more detail [in our online guide](https://cloud-gc.readthedocs.io/en/latest/chapter02_beginner-tutorial/quick-start.html#step-3-log-into-the-server-and-run-geos-chem):

> On Windows, I highly recommend installing Git-BASH to emulate a Linux terminal, so you can follow exactly the same steps as on Mac/Linux. Simply accept all default options during installation, as the goal here is just to use Bash, not Git. Alternatively, you can use MobaXterm, Putty, Linux Subsystem or PowerShell with OpenSSH. But the Git-BASH solution should be the most painless and will also work smoothly in later steps where we add port-forwarding options to connect to Jupyter.

## Tutorial contents used for the workshop

You will follow the comprehensive online tutorials at http://cloud.geos-chem.org. Due to time constraints, the workshop will only cover two essential parts:

- **Part 1: Working with EC2**. Follow the [Quick start guide](https://cloud-gc.readthedocs.io/en/latest/chapter02_beginner-tutorial/quick-start.html). You will launch your own server on AWS, run a demo GEOS-Chem simulation, and plot output data in Jupyter notebooks. 

- **Special instructions for Part 1:** Different from the standard tutorial, in this workshop you will use the free temporary AWS account instead of signing up for your own account; you will terminate the server at the end of this workshop (after finishing both Part 1 and 2), not at the end of Part 1. 

- **Part 2: Working with S3**. Follow [Configuring AWSCLI](https://cloud-gc.readthedocs.io/en/latest/chapter02_beginner-tutorial/awscli-config.html) and [retrieving data from S3](https://cloud-gc.readthedocs.io/en/latest/chapter02_beginner-tutorial/use-s3.html). You will upload your own files to S3 for persistent storage, retrieve GEOS-Chem input data and other public Earth science dataset from S3, and change GEOS-Chem configurations to read the new input data. 

- **Special instructions for Part 2:** When obtaining the AWS CLI credentials, follow the " IAM user account" subsection, not the "root account" subsection.

The slides used for Thursday morning's model clinic are also available [here](https://sites.fas.harvard.edu/~geoschem/Thursday/ThuB_Clinics_zhuang_jiawei_1_mac.pdf), as a summary for the online tutorial.

## Reply your feedbacks here!

You will reply to this survey by simply posting comments within this [GitHub issue](https://help.github.com/articles/about-issues/) (i.e. the current page you are looking at). See the "comment" cell at the bottom of this page, with a big, green "comment" button (need to login to GitHub first).

1. Background: Your university name and how long have you been using GEOS-Chem.
1. Time to finish the EC2 part (Part 1). You may do a rigorous timing, but just a rough number is good enough, such as 30 minutes or 60 minutes.
2. Time to finish the S3 part (Part 2). Again a rough number is good enough. 
3. General comments, if any. (e.g. unclear documentations, confusing web console)
4. Are you planning to use cloud computing for your research? If not, what's your concern (e.g. cost, funding, docs, learning curve, already have compute resources, etc)?

To get a feeling of how the replies would look like, see out past survey at #15. All replies under this issue should adhere to the above user-feedback format. For general discussions on workshop plans, please comment under #23.

**Comment by JiaweiZhuang** [comment]
Here's a sample reply:

Background: XX University, X years of GEOS-Chem experience
Time to finish the EC2 part: X minutes
Time to finish the S3 part: X minutes
General comments: None
Whether to use cloud computing for research: Yes/No/not-sure

**Comment by nairarshad** [comment]
Background: SUNY-Albany, 2 years of GEOS-Chem experience
Time to finish the EC2 part: 20 minutes
Time to finish the S3 part: 30 minutes
General comments: Clear documentation makes this easy to use.
Whether to use cloud computing for research: Yes

**Comment by yiqi0813** [comment]
Background: MIT, 2 months of GEOS-Chem experience
Time to finish the EC2 part: 15 minutes
Time to finish the S3 part: 25 minutes
General comments: Clear instruction step by step.
Whether to use cloud computing for research: Yes

**Comment by Jun-Meng** [comment]
Background: Dal, 2 years of GEOS-Chem experience
Time to finish the EC2 part: 20 minutes
Time to finish the S3 part: 30 minutes
General comments: Clear documentation.
Whether to use cloud computing for research: not  sure

**Comment by jingli0714** [comment]
Background: Harvard, no GEOS-Chem experience
Time to finish the EC2 part: 25 minutes
Time to finish the S3 part: 20 minutes
General comments: None.
Whether to use cloud computing for research: not sure

**Comment by xin-chen-github** [comment]
Background: U. Minnesota, 6 years of GEOS-Chem experience
Time to finish the EC2 part: 20 minutes
Time to finish the S3 part: n/a
General comments: None
Whether to use cloud computing for research: not-sure

**Comment by mariazatko** [comment]
Background: 9 years of GEOS-Chem experience (U. Washington PhD now at Ramboll)
Time to finish the EC2 part: 30 minutes
Time to finish the S3 part: N/A
General comments: Great workshop! Well done!
Whether to use cloud computing for research: Definitely

**Comment by JeremyBirmingham** [comment]
Background: U of Birmingham (UK), 0.5 years of GEOS-Chem experience
Time to finish the EC2 part: 20 minutes
Time to finish the S3 part: 30 minutes
General comments: 1> Great step-by-step tutorial! I will surely recommend this to other students. 
                                2> GC on AWS is really cool and easy to use!
Whether to use cloud computing for research: not-sure (funding is key)

**Comment by yantosca** [comment]
We can close out this issue, as it is more than 2 years old.
