### ISSUE TITLE
[QUESTION] Launch instances via Command Line Interface on Windows

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem-cloud#26]
I thought this issue previously but just realised that it might be worthy of an effort.
From this [link](https://cloud-gc.readthedocs.io/en/latest/chapter03_advanced-tutorial/advanced-awscli.html) we know it is quite convenient to launch an EC2 instance using `aws ec2 run-instances`. However, the solution the [link](https://cloud-gc.readthedocs.io/en/latest/chapter03_advanced-tutorial/advanced-awscli.html) provides only targets Linux/Mac users. For Windows users, scripts modifications are needed. Using the GitBash recommended by the [Quick Start Guide](https://cloud-gc.readthedocs.io/en/latest/chapter02_beginner-tutorial/quick-start.html), we won't have `aws` software by default. Installing `aws` on Windows can be achieved with Anoconda or Miniconda. And a line of code, e.g. `export PATH=.../miniconda3/Scripts:$PATH`, needs to be added to tell the GitBash where to find the `aws`. Besides this, I also found that `--block-device-mapping DeviceName="/dev/sda1",Ebs={VolumeSize=$EBS_SIZE}` does not work properly if launching from Windows but don't know how to resolve it.

**Comment by yantosca** [comment]
Thanks for bringing this up.  We use a shared AWS account here so it is problematic for us to use CLI due to security issues.  So I haven't been able to test this.

**Comment by JiaweiZhuang** [comment]
> Installing `aws` on Windows can be achieved with Anoconda or Miniconda. And a line of code, e.g. `export PATH=.../miniconda3/Scripts:$PATH`, needs to be added to tell the GitBash where to find the `aws`.

Seems like Windows starts to have more native Linux support: https://devblogs.microsoft.com/commandline/announcing-wsl-2/. Would this work for you? In general using Python packages on Windows is annoying... 

> I also found that `--block-device-mapping DeviceName="/dev/sda1",Ebs={VolumeSize=$EBS_SIZE}` does not work properly if launching from Windows but don't know how to resolve it.

What error did you get? You might need to change `/dev/sda1` to something else due to EC2/EBS updates.

> We use a shared AWS account here so it is problematic for us to use CLI due to security issues.

You can still use CLI by making a new IAM user. See "Step 1: Create an AWS IAM User" at https://aws.amazon.com/getting-started/tutorials/backup-to-s3-cli/

**Comment by FeiYao-Edinburgh** [comment]
> What error did you get? You might need to change `/dev/sda1` to something else due to EC2/EBS updates. Try `/dev/nvme0n1p1` (shown by `df`)

Thanks for your reply. I tried again but still got the following similar errors. I personally think it's a problem of different filesystems. I bring this because there might be some potential Windows GitBash users who want to launch an EC2 instance conveniently with flexible EBS. It is totally fine without specifying the EBS, in which case we can only get a default EBS volume.
```
An error occurred (InvalidBlockDeviceMapping) when calling the RunInstances operation: Invalid device name C:/Users/s1855106/AppData/Local/Programs/Git/dev/sda1
An error occurred (InvalidBlockDeviceMapping) when calling the RunInstances operation: Invalid device name C:/Users/s1855106/AppData/Local/Programs/Git/dev/nvme0n1p1
```
Frankly, this issue doesn't bother me too much for the moment. I bring this up supposing maybe you have some interest.

Cheers,
Fei

**Comment by JiaweiZhuang** [comment]
> I tried again but still got the following similar errors.

Does `/dev/xvda` work?

**Comment by FeiYao-Edinburgh** [comment]
> Does `/dev/xvda` work?

Unfortunately No. Similar error, `An error occurred (InvalidBlockDeviceMapping) when calling the RunInstances operation: Invalid device name C:/Users/s1855106/AppData/Local/Programs/Git/dev/xvda`.

**Comment by JiaweiZhuang** [comment]
Hmm why does your device name have a `C:/Users/s1855106/AppData/Local/Programs/Git/` prefix... Would you be able to remove it?

**Comment by FeiYao-Edinburgh** [comment]
That was the information output from GitBash after running `aws ec2 run-instances`. The device name within my script remains as `--block-Connection reset by 129.215.8.197 port 22VolumeSize=$EBS_SIZE}`. I guess this issue is mainly due to Windows machine do not have a proper device for AWS Linux machines to refer to?

**Comment by yantosca** [comment]
Closing this issue.

**Comment by ennui93NN** [comment]
For posterity, if you are in this situation: try prepending `MSYS_NO_PATHCONV=1` to the beginning of your command-line. See [Git for Windows: Known Issues](https://github.com/git-for-windows/build-extra/blob/a9090580ee37686a53166796dffda531041e16f8/ReleaseNotes.md#known-issues).

**Comment by kirang270** [comment]
@yantosca @JiaweiZhuang @FeiYao-Edinburgh  I am getting the same error that @FeiYao-Edinburgh got , I am pasting the error statement I got here kindly help me out if you already know the solution for this . "An error occurred (InvalidBlockDeviceMapping) when calling the RunInstances operation: Invalid device name C:/Program Files/Git/dev/sda1 "> An error occurred (InvalidBlockDeviceMapping) when calling the RunInstances operation: Invalid device name C:/Users/s1855106/AppData/Local/Programs/Git/dev/sda1
