### ISSUE TITLE
[BUG/ISSUE] DUST_DEAD/v2018-04 moved to AFCID/; breaks pre-12.5.0 model

### ISSUE THREAD

**Issue by JiaweiZhuang** [geoschem/geos-chem-cloud#33]
In [HEMCO_data_directories](http://wiki.seas.harvard.edu/geos-chem/index.php/HEMCO_data_directories) I notice that

> In GEOS-Chem 12.5.0 AFCID was separated from the DEAD dust emissions extension to allow for use with offline dust emissions as well.

Now `DUST_DEAD/v2018-04` no longer exist in S3 bucket:

```
$ aws s3 ls --request-payer=requester s3://gcgrid/HEMCO/DUST_DEAD/
                           PRE v2014-07/
                           PRE v2019-06/
```

This is fine for 12.5.0+ that does not read from `DUST_DEAD/v2018-04`, but older version [still reads it](https://github.com/geoschem/geos-chem-unittest/blob/0a4ff6c71d564b5c720d57872348f01eafb52d5a/runs/shared_inputs/fullchem/HEMCO_Config.template.UCX#L2342) 

On Odyssey, it is linked to `../AFCID/v2018-04`
```
$ cd /n/holylfs/EXTERNAL_REPOS/GEOS-CHEM/gcgrid/gcdata/ExtData/HEMCO/DUST_DEAD
$ ls -l v2018-04
lrwxrwxrwx 1 msulprizio jacob_gcst 17 2019-08-12 10:36 v2018-04 -> ../AFCID/v2018-04/
```

However S3 doesn't support symlinks. We can fix it just like [fixing GMI files](https://github.com/geoschem/geos-chem-cloud/blob/GC_12.6.0_doc/scripts/download_data/from_S3/fix_GMI.sh)
```
DATA_ROOT=$HOME/ExtData
aws s3 cp  --request-payer=requester --recursive s3://gcgrid/HEMCO/AFCID/v2018-04/ $DATA_ROOT/HEMCO/AFCID/v2018-04/

cd $DATA_ROOT/HEMCO/DUST_DEAD
rmdir v2018-04
ln -s ../AFCID/v2018-04 ./
```

Note that this issue breaks the HEMCO parser script suggested at https://github.com/geoschem/geos-chem-cloud/issues/25#issuecomment-541446027. The generated script will not download from `AFCID/v2018-04/`as it is not shown in the log file.

**Comment by yantosca** [comment]
We recommend people update to a more recent version than 12.9.0.  I will close out this issue now.
