### ISSUE TITLE
[DISCUSSION] More automatic way to build and update AMI (e.g. via Packer)

### ISSUE THREAD

**Issue by JiaweiZhuang** [geoschem/geos-chem-cloud#34]
If the manual AMI creation is getting annoying and repetitive, there are many ways to automate the process. For example, [Packer](https://github.com/hashicorp/packer) is a popular way to build virtual machine images, just like Docker for building container images. 

Useful materials:
- [Packer tutorial: Build an Image](https://www.packer.io/intro/getting-started/build-image.html)
- [Packer Amazon AMI Builder](https://www.packer.io/docs/builders/amazon.html)
- [Packer Tutorial For Beginners – Automate AMI Creation](https://devopscube.com/packer-tutorial-for-beginners/)
- [Packer AMI Builder examples](https://github.com/awslabs/ami-builder-packer) 

It looks pretty easy to use. The [Packer template](https://www.packer.io/docs/templates/index.html) completely defines the AMI content. You basically just need `source_ami` to specify which base AMI id to start with, the shell commands you want to run on top of this AMI specified in `script` (for long scripts) or `inline` (for short commands), and additional security settings like the AWS key.

 @yantosca This might be worth taking a look at.

**Comment by JiaweiZhuang** [comment]
There is also new "EC2 Image Builder" service that could be useful: https://aws.amazon.com/blogs/aws/automate-os-image-build-pipelines-with-ec2-image-builder/

**Comment by yantosca** [comment]
Closing this issue
