### ISSUE TITLE
[DISCUSSION] A Spack-built software stack for GC-Classic on the AWS cloud

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem-cloud#35]
## Overview
I used Spack to build a software stack for GEOS-Chem "Classic" simulations on AWS.  I am documenting the steps I took here (at least for now).  Maybe later I can make this a README file within the geos-chem-cloud repo.

For some background, see [my video tutorial about installing gcc/gfortran 9.2.0 using Spack](https://www.youtube.com/watch?v=7eMLYKLK9wY&t=1347s).

### 1. Log onto AWS

 * Start a c5 instance (I used ```c5.4xlarge```, with 16 vCPUs)
 * AMI: ```GEOSChem-spack-tutorial-1 (ami-093dcad6c38c2a7f6)```

This will start a cloud instance with Intel Skylake architecture.

### 2. Set up your environment
After logging in to an AWS instance, type these commands:
```
# Unset env vars
unset NETCDF_HOME
unset NETCDF_FORTRAN_HOME
unset GC_BIN
unset GC_F_BIN
unset GC_INCLUDE
unset GC_F_INCLUDE
unset GC_LIB
unset GC_F_LIB

# Install environment-modules (similar to Lmod modules)
# This will let you use "spack load" to load a module set PATH properly
sudo apt install environment-modules

# Initialize environment-modules
. /etc/profile.d/modules.sh

# Set the path to Spack and run the Spack setup script
export SPACK_ROOT=$HOME/spack
source $SPACK_ROOT/share/spack/setup-env.sh 
```

###  3. Build libraries with spack
After completing step 2, follow these steps
```
# Display compiler info.  
# Make sure that gcc@9.2.0 is displayed under linux-ubuntu-skylake_avx512.
spack config get compilers  

# Then type the following commands in this order  (I have added whitespace 
# to better show the different parts of the commands).  
# You can copy & paste these into your terminal window.
#
# Command     module         compiler   options
#------------------------------------------------------------------
spack install netcdf-fortran %gcc@9.2.0
spack install perl           %gcc@9.2.0
spack install flex           %gcc@9.2.0 
spack install cmake          %gcc@9.2.0
spack install gmake          %gcc@9.2.0
spack install gdb            %gcc@9.2.0
spack load    flex
spack load    texinfo
spack install cgdb           %gcc@9.2.0
spack install nco            %gcc@9.2.0
spack install ncview         %gcc@9.2.0 
spack install openjdk        %gcc@9.2.0
spack install tau            %gcc@9.2.0  ~otf2
spack install unzip          %gcc@9.2.0         # Note: Optional
spack load    unzip                             # Note: Optional
spack install emacs          %gcc@9.2.0 +X      # Note: Optional
```
### 4. Post-installation configuration
Add this code to your ```~/.bashrc``` file:
```
# Initialize environment-modules package
if [[ -f /etc/profile.d/modules.sh ]]; then
   source /etc/profile.d/modules.sh
fi

# Initialize spack
export SPACK_ROOT=$HOME/spack
source $HOME/spack/share/spack/setup-env.sh

# Load Spack packages and set relevant environment variables
if [[ -f ~/.init.gc-classic.gfortran92 ]]; then
    source ~/.init.gc-classic.gfortran92
fi

# Alias for loading modules compiled with gfortran 9.2.0
alias load_gf92=`source ~/.init.gc-classic.gfortran92`
```
And then make sure to copy this file to your ```~/init``` folder and to make it executable:
* [init.gc-classic.gfortran92.txt](https://github.com/geoschem/geos-chem-cloud/files/4066182/init.gc-classic.gfortran92.txt)

NOTE: Rename this to ```.init.gc-classic.gfortran92``` and place it in your home directory.

Then when you open a new shell (or type ```source ~/.bashrc```), the modules will be loaded as well.

### 5. AMI
I used the software stack that I created with Spack to create the following AMI:
* ``` GEOSChem-dev-gcc9.2.0``` aka ```ami-0db45eda61a721639```

Use this to initialize your cloud instance.   I will also try to copy this to an S3 bucket.

Also note: this AMI contains 1 day of GEOS-Chem data, but no GEOS-Chem code or UT folders.  It is recommended to download the code and to do a dry-run to get the data for whatever period your simulation needs.

### 6. Further customization
One-time setup:
1. Fork the repository https://github.com/yantosca/aws-env and clone a local copy.
2. Replace the name & email fields of ```aws-env/root/.gitconfig``` with your name & email:
```
[user]
        name = Bob Yantosca
        email = yantosca@seas.harvard.edu
```
3. Also look at the ```root/.bash_aliases``` file to add any of your favorite Unix aliases etc.
4. Push a commit to your local fork of aws-env

Then, once you are in a cloud instance using the ``` GEOSChem-dev-gcc9.2.0``` AMI, clone the fork of your aws-env repo to your home directory.  Then type:
```
~/aws-env/initenv.sh
source ~/.bash_aliases
```
This will apply the settings of your startup scripts.

**Comment by yuexuyan** [comment]
hi Bob,
in your video you picked memory optimised r5.4xlarge, here you chose c5.4xlarge. Which one should be chosen?

**Comment by yuexuyan** [comment]
on my instance, im having trouble with installing tau by spack. Even with skipping install of 'otf2'.

I just happen to know that ubuntu can install tau with simple  '_sodu apt install_' command. 
Is this different from installing tau by spack?  I guess the dependent libraries such as 'pdt' are not installed when installing with _sodu apt install_' command.

**Comment by yuexuyan** [comment]
on my instance, im having trouble with installing tau by spack. Even with skipping install of 'otf2'.

I just happen to know that ubuntu can install tau with simple 'sodu apt install' command.
Is this different from installing tau by spack? I guess the dependent libraries such as 'pdt' are not installed when installing with sodu apt install' command.

and I chosed the same instance with yours (r5.4xlarge) but GEOSChem 12.7.0 tutorial

**Comment by yantosca** [comment]
You may have better luck with the c5 instances, as they are compute-optimized.   Sorry for any confusion.

When you do "sudo apt install" on ubuntu, this installs a pre-built library from a list of libraries that are available. The problem is that you are limited to whatever version and compiler is available.  Using Spack, you can build the compiler and then use that compiler to build libraries.

Can you give me a list of commands that you have tried and where they fail?

**Comment by yuexuyan** [comment]
Thank you very much, I will try c5 later on.

on my r5 instance, I put this line on my terminal after installed other libraries :
'spack install tau  %gcc@9.2.0  ~otf2'

and here are the error messages:

==> Error: Failed to install tau due to ChildError: ProcessError: Command exited with status 2:
    'make' '-j16' 'install'

9 errors found in build log:
 >> 67     grep: ./utils/FixMakefile.info: No such file or directory
  >> 68     grep: ./utils/FixMakefile.sed: No such file or directory
...
      179    Makefile:16: /tmp/ubuntu/spack-stage/spack-stage-tau-2.29-hoglow4i63yuofns3ocleyh4mdlxxh3z/spack-src/x86_64/lib/Makefile.tau-papi-pthread-pdt: No such file or directory
 >> 180    make[1]: *** No rule to make target '/tmp/ubuntu/spack-stage/spack-stage-tau-2.29-hog
            low4i63yuofns3ocleyh4mdlxxh3z/spack-src/x86_64/lib/Makefile.tau-papi-pthread-pdt'.  S
            top.
...
        183    Makefile:16: /tmp/ubuntu/spack-stage/spack-stage-tau-2.29-hoglow4i63yuofns3ocleyh4mdlxxh3z/spack-src/x86_64/lib/Makefile.tau-papi-pthread-pdt: No such file or directory
  >> 184    make[1]: *** No rule to make target '/tmp/ubuntu/spack-stage/spack-stage-tau-2.29-hog
            low4i63yuofns3ocleyh4mdlxxh3z/spack-src/x86_64/lib/Makefile.tau-papi-pthread-pdt'.  Stop.
...
        193    Makefile:16: /tmp/ubuntu/spack-stage/spack-stage-tau-2.29-hoglow4i63yuofns3ocleyh4mdlxxh3z/spack-src/x86_64/lib/Makefile.tau-papi-pthread-pdt: No such file or directory
  >> 194    make[1]: *** No rule to make target '/tmp/ubuntu/spack-stage/spack-stage-tau-2.29-hog
            low4i63yuofns3ocleyh4mdlxxh3z/spack-src/x86_64/lib/Makefile.tau-papi-pthread-pdt'.  S
            top.
...
         197    Makefile:16: /tmp/ubuntu/spack-stage/spack-stage-tau-2.29-hoglow4i63yuofns3ocleyh4mdlxxh3z/spack-src/x86_64/lib/Makefile.tau-papi-pthread-pdt: No such file or directory
  >> 198    make[1]: *** No rule to make target '/tmp/ubuntu/spack-stage/spack-stage-tau-2.29-hoglow4i63yuofns3ocleyh4mdlxxh3z/spack-src/x86_64/lib/Makefile.tau-papi-pthread-pdt'.  S
            top.
...
>> 455    TauBfd.cpp:1020:8: error: 'bfd_get_section_flags' was not declared in this scope; did
             you mean 'bfd_set_section_flags'?
...
>> 459    TauBfd.cpp:1026:17: error: 'bfd_get_section_vma' was not declared in this scope; did
            you mean 'bfd_set_section_vma'?
...
 >> 463    TauBfd.cpp:1032:24: error: 'bfd_get_section_size' was not declared in this scope; did
             you mean 'bfd_set_section_size'?

**Comment by yuexuyan** [comment]
Thank you and by the way, 

What is the application you used in video for opening netcdf with ncview. I see a new window popped up from the edge of your screen.

**Comment by yantosca** [comment]
Sometimes Spack might fail if the internet connection gets interrupted.  Then when it tries to build the library it can't find all the files. Usually if you keep trying to rebuild a library it should eventually work.

The netCDF browser is ncview.  I had 2 screens on the computer where I made the video.  The ncview window popped up in the other screen so I had to manually drag it over.

**Comment by tejendrapsingh** [comment]
Hi!
I am getting an error while building the tau library. Basically, building of libunwind library failed. 
I am posting the terminal output below.

*`==> Error: ProcessError: Command exited with status 2:*
    'make' '-j8'

1 error found in build log:
     838    libtool: link: ar cru .libs/libunwind-coredump.a  coredump/_UCD_acc
            essors.o coredump/_UCD_create.o coredump/_UCD_destroy.o coredump/_U
            CD_access_mem.o coredump/_UCD_elf_map_image.o coredump/_UCD_find_pr
            oc_info.o coredump/_UCD_get_proc_name.o coredump/_UPT_elf.o coredum
            p/_UPT_access_fpreg.o coredump/_UPT_get_dyn_info_list_addr.o coredu
            mp/_UPT_put_unwind_info.o coredump/_UPT_resume.o coredump/_UCD_acce
            ss_reg_linux.o
     839    libtool: link: ranlib .libs/libunwind-coredump.a
     840    libtool: link: /home/tejendrapsingh/spack/lib/spack/env/gcc/gcc -sh
            ared  -fPIC -DPIC  .libs/os-linux.o mi/.libs/init.o mi/.libs/flush_
            cache.o mi/.libs/mempool.o mi/.libs/strerror.o x86_64/.libs/is_fpre
            g.o x86_64/.libs/regname.o x86_64/.libs/Los-linux.o mi/.libs/backtr
            ace.o mi/.libs/dyn-cancel.o mi/.libs/dyn-info-list.o mi/.libs/dyn-r
            egister.o mi/.libs/Ldyn-extract.o mi/.libs/Lfind_dynamic_proc_info.
            o mi/.libs/Lget_accessors.o mi/.libs/Lget_proc_info_by_ip.o mi/.lib
            s/Lget_proc_name.o mi/.libs/Lput_dynamic_unwind_info.o mi/.libs/Lde
            stroy_addr_space.o mi/.libs/Lget_reg.o mi/.libs/Lset_reg.o mi/.libs
            /Lget_fpreg.o mi/.libs/Lset_fpreg.o mi/.libs/Lset_caching_policy.o 
            mi/.libs/Lset_cache_size.o x86_64/.libs/setcontext.o x86_64/.libs/L
            apply_reg_state.o x86_64/.libs/Lreg_states_iterate.o x86_64/.libs/L
            create_addr_space.o x86_64/.libs/Lget_save_loc.o x86_64/.libs/Lglob
            al.o x86_64/.libs/Linit.o x86_64/.libs/Linit_local.o x86_64/.libs/L
            init_remote.o x86_64/.libs/Lget_proc_info.o x86_64/.libs/Lregs.o x8
            6_64/.libs/Lresume.o x86_64/.libs/Lstash_frame.o x86_64/.libs/Lstep
            .o x86_64/.libs/Ltrace.o x86_64/.libs/getcontext.o  -Wl,--whole-arc
            hive ./.libs/libunwind-dwarf-local.a ./.libs/libunwind-elf64.a -Wl,
            --no-whole-archive  -lc -lgcc_s  -g -O2 -nostartfiles -nostdlib   -
            Wl,-soname -Wl,libunwind.so.8 -o .libs/libunwind.so.8.0.1
     841    libtool: link: ( cd ".libs" && rm -f "libunwind-coredump.la" && ln 
            -s "../libunwind-coredump.la" "libunwind-coredump.la" )
     842    x86_64/.libs/Linit.o:(.bss+0x0): multiple definition of `_U_dyn_inf
            o_list'
     843    mi/.libs/dyn-info-list.o:(.bss+0x0): first defined here
*  >> 844    collect2: error: ld returned 1 exit status*
     845    make[2]: *** [Makefile:3252: libunwind.la] Error 1
     846    make[2]: Leaving directory '/tmp/tejendrapsingh/spack-stage/spack-s
            tage-libunwind-1.4.0-7uojdl6pjp76jazdcczbyrrgteyefr3e/spack-src/src
            '
     847    make[1]: *** [Makefile:2163: all] Error 2
     848    make[1]: Leaving directory '/tmp/tejendrapsingh/spack-stage/spack-s
            tage-libunwind-1.4.0-7uojdl6pjp76jazdcczbyrrgteyefr3e/spack-src/src
            '
     849    make: *** [Makefile:603: all-recursive] Error 1

See build log for details:
  /tmp/tejendrapsingh/spack-stage/spack-stage-libunwind-1.4.0-7uojdl6pjp76jazdcczbyrrgteyefr3e/spack-build-out.txt

*==> Error: Failed to install libunwind due to ChildError: ProcessError: Command exited with status 2:
    'make' '-j8'*
1 error found in build log:
     838    libtool: link: ar cru .libs/libunwind-coredump.a  coredump/_UCD_acc
            essors.o coredump/_UCD_create.o coredump/_UCD_destroy.o coredump/_U
            CD_access_mem.o coredump/_UCD_elf_map_image.o coredump/_UCD_find_pr
            oc_info.o coredump/_UCD_get_proc_name.o coredump/_UPT_elf.o coredum
            p/_UPT_access_fpreg.o coredump/_UPT_get_dyn_info_list_addr.o coredu
            mp/_UPT_put_unwind_info.o coredump/_UPT_resume.o coredump/_UCD_acce
            ss_reg_linux.o
     839    libtool: link: ranlib .libs/libunwind-coredump.a
     840    libtool: link: /home/tejendrapsingh/spack/lib/spack/env/gcc/gcc -sh
            ared  -fPIC -DPIC  .libs/os-linux.o mi/.libs/init.o mi/.libs/flush_
            cache.o mi/.libs/mempool.o mi/.libs/strerror.o x86_64/.libs/is_fpre
            g.o x86_64/.libs/regname.o x86_64/.libs/Los-linux.o mi/.libs/backtr
            ace.o mi/.libs/dyn-cancel.o mi/.libs/dyn-info-list.o mi/.libs/dyn-r
            egister.o mi/.libs/Ldyn-extract.o mi/.libs/Lfind_dynamic_proc_info.
            o mi/.libs/Lget_accessors.o mi/.libs/Lget_proc_info_by_ip.o mi/.lib
            s/Lget_proc_name.o mi/.libs/Lput_dynamic_unwind_info.o mi/.libs/Lde
            stroy_addr_space.o mi/.libs/Lget_reg.o mi/.libs/Lset_reg.o mi/.libs
            /Lget_fpreg.o mi/.libs/Lset_fpreg.o mi/.libs/Lset_caching_policy.o 
            mi/.libs/Lset_cache_size.o x86_64/.libs/setcontext.o x86_64/.libs/L
            apply_reg_state.o x86_64/.libs/Lreg_states_iterate.o x86_64/.libs/L
            create_addr_space.o x86_64/.libs/Lget_save_loc.o x86_64/.libs/Lglob
            al.o x86_64/.libs/Linit.o x86_64/.libs/Linit_local.o x86_64/.libs/L
            init_remote.o x86_64/.libs/Lget_proc_info.o x86_64/.libs/Lregs.o x8
            6_64/.libs/Lresume.o x86_64/.libs/Lstash_frame.o x86_64/.libs/Lstep
            .o x86_64/.libs/Ltrace.o x86_64/.libs/getcontext.o  -Wl,--whole-arc
            hive ./.libs/libunwind-dwarf-local.a ./.libs/libunwind-elf64.a -Wl,
            --no-whole-archive  -lc -lgcc_s  -g -O2 -nostartfiles -nostdlib   -
            Wl,-soname -Wl,libunwind.so.8 -o .libs/libunwind.so.8.0.1
     841    libtool: link: ( cd ".libs" && rm -f "libunwind-coredump.la" && ln 
            -s "../libunwind-coredump.la" "libunwind-coredump.la" )
     842    x86_64/.libs/Linit.o:(.bss+0x0): multiple definition of `_U_dyn_inf
            o_list'
     843    mi/.libs/dyn-info-list.o:(.bss+0x0): first defined here
*  >> 844    collect2: error: ld returned 1 exit status*
     845    make[2]: *** [Makefile:3252: libunwind.la] Error 1
     846    make[2]: Leaving directory '/tmp/tejendrapsingh/spack-stage/spack-s
            tage-libunwind-1.4.0-7uojdl6pjp76jazdcczbyrrgteyefr3e/spack-src/src
            '
     847    make[1]: *** [Makefile:2163: all] Error 2
     848    make[1]: Leaving directory '/tmp/tejendrapsingh/spack-stage/spack-s
            tage-libunwind-1.4.0-7uojdl6pjp76jazdcczbyrrgteyefr3e/spack-src/src
            '
     849    make: *** [Makefile:603: all-recursive] Error 1

See build log for details:
  /tmp/tejendrapsingh/spack-stage/spack-stage-libunwind-1.4.0-7uojdl6pjp76jazdcczbyrrgteyefr3e/spack-build-out.txt
Traceback (most recent call last):
  File "/home/tejendrapsingh/spack/lib/spack/spack/build_environment.py", line 813, in child_process
    return_value = function()
  File "/home/tejendrapsingh/spack/lib/spack/spack/installer.py", line 1123, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/home/tejendrapsingh/spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/home/tejendrapsingh/spack/lib/spack/spack/build_systems/autotools.py", line 308, in build
    inspect.getmodule(self).make(*self.build_targets)
  File "/home/tejendrapsingh/spack/lib/spack/spack/build_environment.py", line 131, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/home/tejendrapsingh/spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 2:
    'make' '-j8'

*==> Warning: Skipping build of tau since libunwind failed*
`

**Comment by tejendrapsingh** [comment]
Thanks. 
The issue was resolved [here](https://github.com/spack/spack/issues/16780).
Cheers!

**Comment by tejendrapsingh** [comment]
Hi!

So, I have successfully loaded all the requisite library via spack. 
As detailed in the initial post above, I have copied `.init.gc-classic.gfortran92` in my home directory after editing the `~/.bashrc` file appropriately.
Then, when I am doing `source ~/.bashrc`, I am getting the following error. 
Any help is appreciated. Thanks. 
```

: command not found...
': not a valid identifier
': not a valid identifier
': not a valid identifier
': not a valid identifier
': not a valid identifier
': not a valid identifier
': not a valid identifier
': not a valid identifier
': not a valid identifier
': not a valid identifier
': not a valid identifier
': not a valid identifierUDE
': not a valid identifier
': not a valid identifierRAN_BIN
': not a valid identifierRAN_HOME
': not a valid identifierRAN_INCLUDE
': not a valid identifierRAN_LIB
': not a valid identifier
': not a valid identifier
': not a valid identifier
': not a valid identifier
': not a valid identifierE
': not a valid identifier
': not a valid identifierEADS
': not a valid identifierZE
: command not found...
: command not found...
: command not found...
: command not found...
bash: /home/tejendrapsingh/.init.gc-classic.gfortran92: line 78: syntax error near unexpected token `$'do\r''
bash: /home/tejendrapsingh/.init.gc-classic.gfortran92: line 78: `for f in ${pkg'[@]}; do

```

**My init file:** [init.gc-classic.gfortran92.txt](https://github.com/geoschem/geos-chem-cloud/files/4672777/init.gc-classic.gfortran92.txt)

**Comment by yantosca** [comment]
You might have a syntax error in your .bashrc.

**Comment by yantosca** [comment]
Also, it is often useful to build the Spack libraries with the `target=x86_64` option.  This builds for generic x86-64 chipsets.  Use this if your computer cluster has a number of different nodes with different chip types.
```
# Then type the following commands in this order  (I have added whitespace 
# to better show the different parts of the commands).  
# You can copy & paste these into your terminal window.
#
# Command     module         compiler   options
#------------------------------------------------------------------
spack install netcdf-fortran %gcc@9.2.0 target=x86_64 
spack install perl           %gcc@9.2.0 target=x86_64 
spack install flex           %gcc@9.2.0 target=x86_64 
spack install cmake          %gcc@9.2.0 target=x86_64 
spack install gmake          %gcc@9.2.0 target=x86_64 
spack install gdb            %gcc@9.2.0 target=x86_64 
spack load    flex
spack load    texinfo
spack install cgdb           %gcc@9.2.0 target=x86_64 
spack install nco            %gcc@9.2.0 target=x86_64 
spack install ncview         %gcc@9.2.0 target=x86_64 
spack install openjdk        %gcc@9.2.0 target=x86_64 
spack install tau            %gcc@9.2.0  ~otf2 target=x86_64 
spack install unzip          %gcc@9.2.0  target=x86_64       # Note: Optional
spack load    unzip                                          # Note: Optional
spack install emacs          %gcc@9.2.0 +X  target=x86_64    # Note: Optional
```

**Comment by yantosca** [comment]
This discussion is now superseded by https://github.com/geoschem/geos-chem/issues/637.
