### ISSUE TITLE
[QUESTION]Problem using AWS cloud in a student account

### ISSUE THREAD

**Issue by XiangLiu-github** [geoschem/geos-chem-cloud#37]
Hi all,

I am working on using the AWS cloud to run GEOS-CHEM, I have registered my student account, but when I was launching r5.large after clicking Launch Instances, I got an error saying that "You are not authorized to perform this operation. Encoded authorization failure message: ...".

And when I use a normal account, I am able to launch the EC2. Do you have any ideas about this error?

Screenshot: ![screen](https://user-images.githubusercontent.com/57359052/76130610-f49d3080-5fd0-11ea-8e4c-1ff9443a9a77.PNG)

**Comment by JiaweiZhuang** [comment]
How did you obtain your student account? Is is the educational account without credit card requirement? It might allow limited instance types. Could you launch `t2.micro` instance?

**Comment by XiangLiu-github** [comment]
I registered in https://aws.amazon.com/education/awseducate/, yeah, I was not required with a credit card and there are some remaining credits in my educational account.

I have tried "t2.micro", but it did not work.
screenshot:![scene](https://user-images.githubusercontent.com/57359052/76132656-a9d3e680-5fd9-11ea-8651-4f9b7ffd604d.PNG)

**Comment by JiaweiZhuang** [comment]
I just notice this updated [AWS Services Supported with AWS Educate Starter Account](https://s3.amazonaws.com/awseducate-starter-account-services/AWS_Educate_Starter_Accounts_and_AWS_Services.pdf) saying that:

```
Starter Accounts support only following instance types:
"t2.small","t2.micro","t2.nano","m4.large","c4.large","c5.large
","m5.large","t2.medium","m4.xlarge","t2.nano","c4.xlarge","c
5.xlarge","t2.2xlarge","m5.2xlarge","t2.large","t2.xlarge","m5.
xlarge","a1.medium","a1.large","a1.xlarge"
No Spot Instances supported
No Reserved Instances purchasessupported
```

**Comment by XiangLiu-github** [comment]
Yeah, I see, the strange thing is that I could launch a raw "t2.small" instance, but I cannot use the AIMs to launch a "t2.small" instance with GEOS-CHEM tutorial.

**Comment by yantosca** [comment]
I will close out this issue for now.  Feel free to reopen.

**Comment by neyranaz** [comment]
Hello, I have the same issue. I also tried usingc5.XLarge and it didn't work. Is this bc we are running an AIM from an Educate Account? How did you solve it?

**Comment by lizziel** [comment]
Hi @neyranaz , we never heard back with resolution on this. I suggest contacting AWS Educate via this [contact link](https://aws.amazon.com/education/awseducate/contact-us/) and following up here for others to see what the resolution is.

**Comment by yantosca** [comment]
My sense is that the student accounts don't allow for all instances.  You might need to have a credit card backed account.  But you should also be able to use at least the $100 of research credits, and possibly obtain more research credits for your work as described here: https://aws.amazon.com/research-credits/faq/.

**Comment by neyranaz** [comment]
You are right Bob, since march, it does not allow anymore for all instances and it doesn't either allow to launch public images (even with the $100 credit). So new students might be better off running the tutorial from a conventional account and paying the 1 cent. (But not running anything else).

**Comment by yantosca** [comment]
Thanks.  I can close this issue out if there is nothing else.

**Comment by yantosca** [comment]
I guess AWS is cracking down on student use.  Sorry to hear.  If we hear of any other ways forward we can let you know.
