### ISSUE TITLE
[BUG/ISSUE] Dryrun error in GEOS-Chem 12.7.0 on c5.4xlarge

### ISSUE THREAD

**Issue by yuexuyan** [geoschem/geos-chem-cloud#38]
## Describe the issue
dryrun error in GEOSChem 12.7.0 geosfp_2x2.5_CO2 simulation on a c5.4xlrge AWS instance 

## To Reproduce
Include the steps that must be done in order to reproduce the observed behavior:

commands
1. cd ~/tutorial/UT/per/CopyRunDirs.input 
2. vim CopyRunDirs.input (select geosfp_2x2.5_CO2 simulation and set time)
3. ./gcCopyRunDirs 
4. cd ~/tutorial/geosfp_2x25_CO2
5. vim HEMCO_Config.rc (turn GFED and FINN off), 
6. vim input.geos (set latitude & longitude and turn on plane flt diag)
7. vim HISTORY.rc (set the frequency and duration of the Restart COLLECTION and the CO2 COLLECTION ; change the SpeciesConc COLLECTION to ALL)
8. make realclean
9. make -j16 build
10. ./geos --dryrun > log.dryrun

## Error messages:
```
At line 1027 of file input_mod.F
Fortran runtime error: Expected INTEGER for item 1 in formatted transfer, got REAL
(i10)
 ^
```
Error termination. Backtrace:
```
#0  0x14c3441e820b in require_type
        at /tmp/ubuntu/spack-stage/spack-stage-gcc-9.2.0-ss6lvrx5xrdw2fvz537f7alyak3cym2x/spack-src/libgfortran/io/transfer.c:1328
#1  0x14c3441eb27d in require_type
        at /tmp/ubuntu/spack-stage/spack-stage-gcc-9.2.0-ss6lvrx5xrdw2fvz537f7alyak3cym2x/spack-src/libgfortran/io/transfer.c:1320
#2  0x14c3441eb27d in formatted_transfer_scalar_write
        at /tmp/ubuntu/spack-stage/spack-stage-gcc-9.2.0-ss6lvrx5xrdw2fvz537f7alyak3cym2x/spack-src/libgfortran/io/transfer.c:1945
#3  0x14c3441eb64b in formatted_transfer
        at /tmp/ubuntu/spack-stage/spack-stage-gcc-9.2.0-ss6lvrx5xrdw2fvz537f7alyak3cym2x/spack-src/libgfortran/io/transfer.c:2335
#4  0x14c3441e7ee5 in wrap_scalar_transfer
        at /tmp/ubuntu/spack-stage/spack-stage-gcc-9.2.0-ss6lvrx5xrdw2fvz537f7alyak3cym2x/spack-src/libgfortran/io/transfer.c:2369
#5  0x14c3441e7ee5 in wrap_scalar_transfer
        at /tmp/ubuntu/spack-stage/spack-stage-gcc-9.2.0-ss6lvrx5xrdw2fvz537f7alyak3cym2x/spack-src/libgfortran/io/transfer.c:2346
#6  0x4c56ef in read_grid_menu
        at /home/ubuntu/tutorial/Code.GC-classic/GeosCore/input_mod.F:1027
#7  0x4cb941 in __input_mod_MOD_read_input_file
        at /home/ubuntu/tutorial/Code.GC-classic/GeosCore/input_mod.F:174
#8  0x48f56c in geos_chem
        at /home/ubuntu/tutorial/Code.GC-classic/GeosCore/main.F:386
#9  0x4033c6 in ???
#10  0x14c342f8eb96 in ???
#11  0x4033f9 in ???
#12  0xffffffffffffffff in ???
```

## Required information
Please include the following:
 - GEOS-Chem version you are using [12.7.0]
 - Compiler version that you are using [gfortran 9.2.0] 
 - netCDF and netCDF-Fortran library version: netcdf-c@4.7.3; netcdf-fortran@4.5.2
 - Computational environment [e.g. a cluster, or the AWS cloud]
 - The Amazon Machine Image (AMI) ID that you used
 - Are you using "out of the box" code, or have you made modifications? no

## Input and log files to attach

[CopyRunDirs.input.txt](https://github.com/geoschem/geos-chem-cloud/files/4333241/CopyRunDirs.input.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem-cloud/files/4333242/HEMCO_Config.rc.txt)
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem-cloud/files/4333243/HISTORY.rc.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem-cloud/files/4333244/input.geos.txt)
[lastbuild.txt](https://github.com/geoschem/geos-chem-cloud/files/4333245/lastbuild.txt)
[log.dryrun.txt](https://github.com/geoschem/geos-chem-cloud/files/4333246/log.dryrun.txt)

 - The lastbuild file
 - The input.geos file
 - The HEMCO_Config.rc file
 - The GEOS-Chem "Classic" log file
 - The HEMCO.log file

**Comment by yantosca** [comment]
Thanks for writing.  I think I see the issue.  Your grid definition is:
```
%%% GRID MENU %%%       :
Grid resolution         : 2.0x2.5
Longitude min/max       : 110.0 -160.0
Latitude  min/max       :  -47.0  30.0
 Half-sized polar boxes?: T
Number of levels        : 47
Nested grid simulation? : F
 Buffer zone (N S E W ) :  0  0  0  0
```
But this is tripping an error because the min longitude is greater than the max longitude.  This would have generated an error message but apparently there is a Fortran Format error in the conversion of number to string.  

I don't think that FlexGrid can yet handle wrapping around the date line gracefully.  You can try another grid definition.

**Comment by yantosca** [comment]
I will close out this issue.  Feel free to reopen.
