### ISSUE TITLE
[QUESTION] Data Version Selection, affecting data download and run. (Setting up data version)

### ISSUE THREAD

**Issue by neyranaz** [geoschem/geos-chem-cloud#39]
We are trying to perform a 4x5 aerosol only simulation following the [workflow](https://cloud-gc.readthedocs.io/en/latest/chapter02_beginner-tutorial/research-workflow.html) in the tutorial for 20140101, however we are having some issues when pulling data from the repository to our EC2, and when trying to run it using ./geos

Specifically, we have been using the last lines from deploy_GC.sh to get the files that we need from the file specification output created by the dry run. However, when running ./geos, we found that the GFED4 files are not being pulled correctly.  For instance, we wanted to include GFED4 emissions for 2014, which are only available in version /v2015-10/, but the download_data.py code was trying to pull these emissions from the 2020 version as  /v2020-02/2014/GFED4_gen.025x025.201401.nc.  This issue, also prevent the run from occurring, even after the "manual" download of the omitted files, since it tries to pull the data from a v2020-02/2014/ local directory and not from the /v2015-10/. 

We were thinking that this might be due to omitted specifications in the input for the run and dry run. This might be triggering the use of the latest version of GFED4, and not the use of the one where the data is. So we were wondering where can we specify this to be able to download and run the data correctly. We were thinking of doing it in HEMCO_Config.rc , but still need some insight. 

GFED4 version, not specified in run --> dry run pulls latest version of GFED4 --->Data not available in latest version--->Run and Data download not working. 

```
Errors in HEMCO.log: 
Cannot find file for current simulation time: /home/ubuntu/ExtData/HEMCO/GFED4/v2020-02/2014/GFED4_gen.025x025.201401.nc
HEMCO ERROR: Error encountered in routine HCOIO_Read_Std!
HEMCO ERROR: Error in HCOIO_DATAREAD called from HEMCO ReadList_Fill: GFED_TEMP
HEMCO ERROR: Error in ReadList_Fill (3) called from HEMCO ReadList_Read
```

**Comment by yantosca** [comment]
Thanks for writing.  A couple of things:

1. We have fixed a few bugs in the dry-run (due to errors in HEMCO) in GEOS-Chem 12.9.2.  I think the dry-run should now be able to pull all of the file, and the deploy_GC.sh is now more or less obsolete.

2. Try changing the GFED4 directory in your HEMCO_Config.rc file from v2020-02 back to v2015-10 and doing a new dry-run from scratch for year 2014.  That should grab the biomass burning data.

Am also tagging @WilliamDowns, who is taking over as point person for our GEOS-Chem cloud efforts.  He is going to be making a new AMI for 12.9.2 shortly.

**Comment by neyranaz** [comment]
Thank you @Yantosca, this answered my question!

In case others were having the same issue, as recommended by Bob, we modified HEMCO_config.rc to able to pull those data that weren't being pulled correctly due to differences in the GC input repository. This allowed the correct specification of those files that were needed, when performing the Dry-Run. By doing this, it was much faster to download the files needed. 

For example, as Bob explained, to be able to pull the data of interest, we could modify the line below, as well as any additional lines for other species. 

```
`#==============================================================================
# --- GFED biomass burning emissions (Extension 111)
# NOTE: These are the base emissions in kgDM/m2/s.
#==============================================================================
(((GFED4
111 GFED_TEMP       $ROOT/GFED4/v2015-10/$YYYY/GFED4_gen.025x025.$YYYY$MM.nc  DM_TEMP       1997-2016/1-12/01/0    RF xy kgDM/m2/s * - 1 1`
```

**Comment by yantosca** [comment]
Thanks @neyranaz.  BTW, I think the GFED4/v2020-02 data hadn't been synced to the AWS s3://gcgrid bucket.  We are working on forcing that sync now, so the data will eventually be copied over.

**Comment by yantosca** [comment]
I will close out this issue for now but please feel free to reopen.
