### ISSUE TITLE
[QUESTION] Using the "official" GEOS-Chem images on Docker Hub starting in 13.0.0

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/geos-chem-cloud#42]
Starting in 13.0.0, pre-built docker images for GCClassic and GCHP are deployed to Docker Hub on releases. I see that geos-chem-cloud is using  `geoschem/gchp_model`. Could this be updated to use the new auto-deployed images?

**Comment by yantosca** [comment]
Closing this issue
