### ISSUE TITLE
[BUG/ISSUE] Invalid time stamp in GC-Classic restart file

### ISSUE THREAD

**Issue by StrangeFrog** [geoschem/geos-chem-cloud#43]
# Report a technical issue for GEOS-Chem on the AWS cloud

##  HEMCO ERROR: Cannot find field with valid time stamp
**Hello, this picture shows the problem I encountered.**
![image](https://user-images.githubusercontent.com/93367256/145839902-86475008-70aa-48a9-afda-04de8bb25b30.png)

**This picture shows the list of files in my current folder.**
![image](https://user-images.githubusercontent.com/93367256/145840192-08bf6c21-34b3-413b-b8f8-1a5b3e4f540a.png)

This picture shows the modified content of the input。geo file.
![image](https://user-images.githubusercontent.com/93367256/145840457-f1ee7411-6533-4cae-b61b-1fc00d47cb8a.png)

## To Reproduce
 I tried to search this question in Google browser and got some reference answers（http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_restart_files#Restart_files_in_GEOS-Chem_12）. Unfortunately, I still haven't solved this problem.

 Hope to get help, thank you.

**Comment by lizziel** [comment]
It looks like your simulation starts on May 1 but your restart file is for April 1. The restart file date must match your simulation start date. Did you try to fix this problem using the instructions at the wiki page you linked to and it did not work?

**Comment by StrangeFrog** [comment]
> It looks like your simulation starts on May 1 but your restart file is for April 1. The restart file date must match your simulation start date. Did you try to fix this problem using the instructions at the wiki page you linked to and it did not work?

Thank you for your reply. I have made two more attempts to solve the problem according to your message.

1. I adjusted the simulation time, and I downloaded the data again. But this problem has not been solved.

![image](https://user-images.githubusercontent.com/93367256/145918779-003d6057-7362-4ce9-8d22-154e051d268f.png)
![image](https://user-images.githubusercontent.com/93367256/145919494-d798332b-b5af-443d-a19b-ee84a588fce0.png)
![image](https://user-images.githubusercontent.com/93367256/145919421-05cf6e42-72d7-403e-8dfa-ff733186a25c.png)

2. For wiki link (http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_restart_files#Restart_files_in_GEOS-Chem_12), i have captured these information in web as  pictures.
![Screenshot from 2021-12-14 10-05-24](https://user-images.githubusercontent.com/93367256/145919815-66e937a1-9a11-4962-ab12-c19347b8dbf4.png)

Then， I tried to change Restart.fields:  '''SpeciesRst_?ALL?   to Restart.fields:  '''SPC_?ALL? .  And i have a error again.

![Screenshot from 2021-12-14 10-10-01](https://user-images.githubusercontent.com/93367256/145920233-4b5d3790-f344-4375-9dd0-b3360142638a.png)
![image](https://user-images.githubusercontent.com/93367256/145920543-33697d75-8cf4-4300-8192-39a93cb1b3c5.png)
![Screenshot from 2021-12-14 10-15-25](https://user-images.githubusercontent.com/93367256/145920941-afad8713-5393-4bde-ab0e-970c43f70aef.png)

Hope to get a solution to the problem.

**Comment by StrangeFrog** [comment]
It's crazy that this problem happens again and again.  I can't understand why I should check hemco_ Config. rc
**error**
![image](https://user-images.githubusercontent.com/93367256/145931082-ec1005e1-fe20-46f3-af78-925d20dec011.png)

**hemco_ Config. rc**

![image](https://user-images.githubusercontent.com/93367256/145931513-89037877-a76f-4f52-b944-3a719d76cf2b.png)
![image](https://user-images.githubusercontent.com/93367256/145931544-970ebcd7-ebe5-4973-bb50-cd14c2d7afe5.png)

![image](https://user-images.githubusercontent.com/93367256/145931577-4564dada-6569-40f1-8caa-7a004b7ab3a2.png)

![image](https://user-images.githubusercontent.com/93367256/145931742-7f16d197-2a59-4313-a43b-6ccb9cdf989f.png)

****hemco_ Config. rc****
![image](https://user-images.githubusercontent.com/93367256/145932047-98e85b71-7ba2-4465-87ac-8a35881cf09a.png)

**Comment by lizziel** [comment]
Hi @StrangeFrog, what version are you using? It would also be helpful if you upload your config and log files by adding extension '.txt' and dragging and dropping into the comment box. Finally, how did you generate your restart file?

**Comment by yantosca** [comment]
@StrangeFrog, I'd recommend starting fresh with a more recent version (like 13.3.1), so that you get a good restart file.

**Comment by StrangeFrog** [comment]
Thank you for your reply.  I reconfigured geochem according to the method from yantosca. But I encountered this problem again. I guess there is a problem with my steps. 

1. Show me the configured process.

     -  First, I launched a geoschem service in AWS.
     -  Then, I configured the compilation environment according to the following code
              `$ mkdir ~/GC  # make you own folder instead using the "tutorial" folder.`
              `$ cd ~/GC`
              `$ git clone https://github.com/geoschem/GCClassic.git Code.GC`
              `$ cd Code.GC`
              `$ git submodule update --init --recursive`
              `$ cd ~/GC/Code.GC/run`
              `$ ./createRunDir.sh`
              `$ cd ~/GC/rundirs/YOUR_RUN_DIRECTORY`
              `$ cd build/`
              `$ cmake ../CodeDir -DRUNDIR=..`
              `$ make -j`
              `$ make install`
              `$ cd ..`
              `$ ls`
      -  I modify the simulation time in the input.geo file.
      - Then execute the following code.
             `$ ./gcclassic --dryrun | tee log.dryrun`
             `$ ./download_data.py log.dryrun --aws`
     -  After executing the above code, there will be some missing files, and then I execute the following code.
             `$ ./gcclassic --dryrun > log.dryrun.2`
             `$   grep "NOT FOUND"  	log.dryrun.2`
             `$  ./download_data.py log.dryrun.2 washu`
     -  Finally, I'll get the restart file and run the simulation and get the following errors.
            `$ ./gcclassic | tee run.log`
![image](https://user-images.githubusercontent.com/93367256/146114094-1a20c5b0-bef5-428d-b969-c501ca30b597.png)


2.  Screenshot of current folder list and some files
![image](https://user-images.githubusercontent.com/93367256/146116670-abfbe0e5-be6d-44e1-8851-a70c86577e13.png)

**HEMco_Configure.rc**
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem-cloud/files/7716240/HEMCO_Config.txt)

**run.log**
[run.txt](https://github.com/geoschem/geos-chem-cloud/files/7716243/run.txt)

**HISTORY.rc**
[HISTORY.txt](https://github.com/geoschem/geos-chem-cloud/files/7716247/HISTORY.txt)

**inpur.geos**
[input.txt](https://github.com/geoschem/geos-chem-cloud/files/7716261/input.txt)


We look forward to your reply and thank you again.

**Comment by StrangeFrog** [comment]
Thank you very much. I have solved this problem.

**Comment by lizziel** [comment]
Glad you were able to solve it. Could you follow-up with a post here on what ended up working to fix the issue? This may help other users in the future who experience the same problem.

**Comment by StrangeFrog** [comment]
1. The first step to solve this problem is to determine that there is a match between the restart file and the simulation start time.

2. Check the internal time of restart file,
    `$ ncdump -h GEOSChem.SpeciesConc.20190701_0000z.nc4`
     

    > netcdf GEOSChem.SpeciesConc.20190701_0000z {
dimensions:
      time = UNLIMITED ; // (1 currently)
      lev = 72 ;
      ilev = 73 ;
      lat = 46 ;
      lon = 72 ;
variables:
      double time(time) ;
              time:long_name = "Time" ;
    time:units = "minutes since 2019-07-01 00:00:00 UTC" ;
              time:calendar = "gregorian" ;
              time:axis = "T" ;
...


**Make sure “ time:units = minutes since 2019-07-01 00:00:00 UTC” and the file name and time are consistent.**

If the time is inconsistent, please modify it（https://github.com/geoschem/geos-chem/issues/712）.
