### ISSUE TITLE
[QUESTION] LOG with unique file paths written to: log.dryrun.unique

### ISSUE THREAD

**Issue by ZhongWanqin** [geoschem/geos-chem-cloud#44]
# Ask a question about running GEOS-Chem on the AWS cloud
Hi！I run GEOS-Chem based on GEOSChem_13.2.1_tutorial_20211005. I have got the output result successfully. But when I run it again, I encounter two problems that i have no idea to solve.
1
./gcclassoc --dryrun > log.dryrun
Log with unique file paths written to: log.dryrun.unique

2
I want to demonstrate CH4 with horizontal resolution of 0.5*0.625. But it showed that some data (ExtData/HEMCO/SAMPLE_BCs/v2021-07/CH4/GEOSChem.BoundaryConditions.YYYYMMDD_HHNNz.nc4)does not exist in amazon or washu.

**Comment by yantosca** [comment]
Thanks for writing @ZhongWanqin, and sorry for the very late reply!

You can also download data from the WashU server (http://geoschemdata.wustl.edu) as described in https://geos-chem.readthedocs.io.  The AWS S3 bucket only has a subset of the available data but the WashU data has all of the available data and met fields.

Also the sample BC files are just there for you to start a simulation.  We recommend creating your own BC files from the output of a simulation on the global grid.

**Comment by yantosca** [comment]
Closing out this issue
