### ISSUE TITLE
GCHP on AWS cloud

### ISSUE THREAD

**Issue by JiaweiZhuang** [geoschem/geos-chem-cloud#9]
This is a long-term goal. Just put it here for record. Will focus on GC-classic right now.

TODO:
1. Compile and run GCHP with gfortran. 
2. Make the performance acceptable. MAPL is in favor of the latest ifort and doesn't seem to like older versions or other compilers. 
2. Run large-scale MPI jobs with CfnCluster (see also #6)

**Comment by Jun-Meng** [comment]
Hi,
![Screen Shot 2019-10-18 at 2 37 41 PM](https://user-images.githubusercontent.com/22326325/67123094-f3e83700-f1b4-11e9-9e01-1e236fc37a81.png)
I'm following the tutorial to run GCHP on EC2 using GCHP container image (container_geoschem_tutorial_20181213). I'm using singularity container. I ran into the following error, as shown in the attached screenshot. Anybody else had the same problem? Thanks

**Comment by JiaweiZhuang** [comment]
@Jun-Meng Could you upload the complete log file? It seems a memory issue and might be solved by using a bigger instance with more memory.

That GCHP container image is too old so I don't recommend using that for serious research purpose. I am working on the cloud-GCHP paper; once it is done I will update the image accordingly, likely in early next year.

**Comment by JiaweiZhuang** [comment]
@Jun-Meng I highly recommend waiting until CMake and Continuous Integration are implemented for GCHP (geoschem/gchp#36). That will avoid many debugging hassles.

**Comment by Jun-Meng** [comment]
Thanks Jiawei. I will try to use a larger memory instance. It's not on a serious research purpose so I think I will just wait the new GCHP to be released.

**Comment by yantosca** [comment]
@WilliamDowns has been making lots of progress in getting GCHP to run on the cloud since this issue was posted.  I will close out this issue so that we can open new issues.  GCHP has changed a lot since 2018.
